[package]
name = "bio_index_formats"
version = "0.1.2"
authors = ["Roman Valls Guimera <brainstorm@nopcode.org>", "Christian Pérez-Llamas <chrispz@gmail.com>"]
edition = "2018"

[dependencies]
nom = "5.1.0"
