[package]
name = "bio-index-formats"
version = "0.1.0"
authors = ["Roman Valls Guimera <brainstorm@nopcode.org>", "Christian Pérez-Llamas <chrispz@gmail.com>"]
edition = "2018"

[dependencies]
nom = "5.1.0"
rust-htslib = "0.26.1"