[package]
name = "bio_index_formats"
version = "0.1.3"
authors = ["Roman Valls Guimera <brainstorm@nopcode.org>", "Christian Pérez-Llamas <chrispz@gmail.com>"]
edition = "2018"

[dependencies]
nom = "6.1.2"
bam-builder = "0.1.3"